### ISSUE TITLE
property is_awake fails self

### ISSUE THREAD

**Issue by PaulskPt** [peter-l5/SH1107#5]
Hi Peter, thank you for publishing this driver for the SH1107.
I downloaded the sh1107.py file. When I started to use it, it crashed.
Investigation revealed that the @property is_awake doesn't contain 'self' 
 `def is_awake() -> bool:`. 
When I changed it into:  `def is_awake(self) -> bool:` the problem was solved.

**Comment by peter-l5** [comment]
Hi @PaulskPt, 
Thank you for letting me know about this problem and for sharing a resolution. The fix you suggest looks good to me so I have updated the code accordingly.
best
Peter
